package com.eteng.mobileorder.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CUSTOMER_INFO.
 */
public class CustomerInfo {

    private Long id;
    private String customerTel;
    private String customerAddr;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CustomerInfo() {
    }

    public CustomerInfo(Long id) {
        this.id = id;
    }

    public CustomerInfo(Long id, String customerTel, String customerAddr) {
        this.id = id;
        this.customerTel = customerTel;
        this.customerAddr = customerAddr;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCustomerTel() {
        return customerTel;
    }

    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    public String getCustomerAddr() {
        return customerAddr;
    }

    public void setCustomerAddr(String customerAddr) {
        this.customerAddr = customerAddr;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
