package com.eteng.mobileorder.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CUSTOMER_INFO.
 */
public class CustomerInfo {

    private Long id;
    private String customerTel;
    private String customerAddr;
    private Long sellerId;

    // KEEP FIELDS - put your custom fields here
	private String orderTimes;// 点单次数
	private String totalConsumption;// 消费总额
    // KEEP FIELDS END

    public CustomerInfo() {
    }

    public CustomerInfo(Long id) {
        this.id = id;
    }

    public CustomerInfo(Long id, String customerTel, String customerAddr, Long sellerId) {
        this.id = id;
        this.customerTel = customerTel;
        this.customerAddr = customerAddr;
        this.sellerId = sellerId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCustomerTel() {
        return customerTel;
    }

    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    public String getCustomerAddr() {
        return customerAddr;
    }

    public void setCustomerAddr(String customerAddr) {
        this.customerAddr = customerAddr;
    }

    public Long getSellerId() {
        return sellerId;
    }

    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    // KEEP METHODS - put your custom methods here
	public String getOrderTimes() {
		return orderTimes;
	}

	public void setOrderTimes(String orderTimes) {
		this.orderTimes = orderTimes;
	}

	public String getTotalConsumption() {
		return totalConsumption;
	}

	public void setTotalConsumption(String totalConsumption) {
		this.totalConsumption = totalConsumption;
	}
    // KEEP METHODS END

}
