package com.eteng.mobileorder.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.ArrayList;

import android.os.Parcel;
import android.os.Parcelable;

// KEEP INCLUDES END
/**
 * Entity mapped to table DISH_INFO.
 */
public class DishInfo implements Parcelable {

	private long dishId;
	private String dishName;
	private Float price;
	private String dishImgPath;
	private String createPerson;
	private String createDate;
	private Float discountPrice;
	private String dishSummary;
	private Long dishCategory;
	private String dishStock;
	private Integer dishOrder;
	private String dishSerial;
	private String dishStatus;
	private String dishType;

	// KEEP FIELDS - put your custom fields here
	/**
	 * 备注信息
	 */
	private ArrayList<String> remark = new ArrayList<String>();

	/**
	 * 选择状态
	 */
	private boolean choiceState = false;

	// KEEP FIELDS END

	public DishInfo() {
	}

	public DishInfo(long dishId) {
		this.dishId = dishId;
	}

	public DishInfo(long dishId, String dishName, Float price,
			String dishImgPath, String createPerson, String createDate,
			Float discountPrice, String dishSummary, Long dishCategory,
			String dishStock, Integer dishOrder, String dishSerial,
			String dishStatus, String dishType) {
		this.dishId = dishId;
		this.dishName = dishName;
		this.price = price;
		this.dishImgPath = dishImgPath;
		this.createPerson = createPerson;
		this.createDate = createDate;
		this.discountPrice = discountPrice;
		this.dishSummary = dishSummary;
		this.dishCategory = dishCategory;
		this.dishStock = dishStock;
		this.dishOrder = dishOrder;
		this.dishSerial = dishSerial;
		this.dishStatus = dishStatus;
		this.dishType = dishType;
	}

	public long getDishId() {
		return dishId;
	}

	public void setDishId(long dishId) {
		this.dishId = dishId;
	}

	public String getDishName() {
		return dishName;
	}

	public void setDishName(String dishName) {
		this.dishName = dishName;
	}

	public Float getPrice() {
		return price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public String getDishImgPath() {
		return dishImgPath;
	}

	public void setDishImgPath(String dishImgPath) {
		this.dishImgPath = dishImgPath;
	}

	public String getCreatePerson() {
		return createPerson;
	}

	public void setCreatePerson(String createPerson) {
		this.createPerson = createPerson;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public Float getDiscountPrice() {
		return discountPrice;
	}

	public void setDiscountPrice(Float discountPrice) {
		this.discountPrice = discountPrice;
	}

	public String getDishSummary() {
		return dishSummary;
	}

	public void setDishSummary(String dishSummary) {
		this.dishSummary = dishSummary;
	}

	public Long getDishCategory() {
		return dishCategory;
	}

	public void setDishCategory(Long dishCategory) {
		this.dishCategory = dishCategory;
	}

	public String getDishStock() {
		return dishStock;
	}

	public void setDishStock(String dishStock) {
		this.dishStock = dishStock;
	}

	public Integer getDishOrder() {
		return dishOrder;
	}

	public void setDishOrder(Integer dishOrder) {
		this.dishOrder = dishOrder;
	}

	public String getDishSerial() {
		return dishSerial;
	}

	public void setDishSerial(String dishSerial) {
		this.dishSerial = dishSerial;
	}

	public String getDishStatus() {
		return dishStatus;
	}

	public void setDishStatus(String dishStatus) {
		this.dishStatus = dishStatus;
	}

	public String getDishType() {
		return dishType;
	}

	public void setDishType(String dishType) {
		this.dishType = dishType;
	}

	// KEEP METHODS - put your custom methods here

	public ArrayList<String> getRemark() {
		return remark;
	}

	public boolean isChoiceState() {
		return choiceState;
	}

	public void setChoiceState(boolean choiceState) {
		this.choiceState = choiceState;
	}

	public void setRemark(ArrayList<String> remark) {
		this.remark = remark;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(this.dishId);
		dest.writeString(this.dishName);
		dest.writeFloat(this.price);
		dest.writeString(this.dishImgPath);
		dest.writeString(this.createPerson);
		dest.writeString(this.createDate);
		dest.writeFloat(this.discountPrice);
		dest.writeString(this.dishSummary);
		dest.writeLong(this.dishCategory);
		dest.writeString(this.dishStock);
		dest.writeInt(this.dishOrder);
		dest.writeString(this.dishSerial);
		dest.writeString(this.dishStatus);
		dest.writeString(this.dishType);
		dest.writeList(this.remark);
		dest.writeByte(this.choiceState ? (byte) 1 : (byte) 0);
	}

	@SuppressWarnings("unchecked")
	private DishInfo(Parcel in) {
		this.dishId = in.readLong();
		this.dishName = in.readString();
		this.price = in.readFloat();
		this.dishImgPath = in.readString();
		this.createPerson = in.readString();
		this.createDate = in.readString();
		this.discountPrice = in.readFloat();
		this.dishSummary = in.readString();
		this.dishCategory = in.readLong();
		this.dishStock = in.readString();
		this.dishOrder = in.readInt();
		this.dishSerial = in.readString();
		this.dishStatus = in.readString();
		this.dishType = in.readString();
		this.remark = in.readArrayList(String.class.getClassLoader());
		this.choiceState = (in.readByte() == 1 ? true : false);
	}

	public static final Parcelable.Creator<DishInfo> CREATOR = new Creator<DishInfo>() {
		public DishInfo createFromParcel(Parcel source) {
			return new DishInfo(source);
		}

		@Override
		public DishInfo[] newArray(int size) {
			// TODO Auto-generated method stub
			return new DishInfo[size];
		}
	};

	@Override
	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}
	// KEEP METHODS END

}
